### ISSUE TITLE
ROUTE/인원, 차량 선택

### ISSUE THREAD

**Issue by jungo0** [jungo0/Budy#11]
## 요구사항 ID

ROUTE/인원, 차량 선택

## 요구사항
인원 차량을 선택할 수 있는 페이지를 제작한다. 

## 상세 요구사항

- 인원 선택 카운트 버튼을 제작한다. 
- 차량 선택할 수 있는 슬라이드 버튼을 제작한다.

## TODO
- [ ] 인원,차량선택 페이지 레이아웃 제작
- [ ] 인원 선택 카운트 버튼 제작 
- [ ] 차량 선택 슬라이드 버튼 제작
