### ISSUE TITLE
ROUTE/노선 취소

### ISSUE THREAD

**Issue by ljg980708** [jungo0/Budy#13]
## 요구사항 ID

ROUTE/노선 취소

## 요구사항

회원이 등록한 노선을 취소한다.

## 상세 요구사항

- 회원 본인이 생성한 노선을 취소할 수 있다.
- 본인이 생성하지 않은 노선은 취소할 수 없다.
- 운행 혹은 운행 예정에 들어간 노선은 취소할 수 없다.

## TODO
- [ ] 생성된 노선을 취소할 수 있다.
- [ ] 본인이 생성하지 않은 노선은 취소할 수 없다.
- [ ] 운행 혹은 운행 예정에 들어간 노선은 취소할 수 없다.
