### ISSUE TITLE
ROUTE/노선 참여

### ISSUE THREAD

**Issue by ljg980708** [jungo0/Budy#24]
## 요구사항 ID

ROUTE/노선 참여

## 요구사항

생성된 노선을 참여할 수 있다.

## 상세 요구사항

- 생성된 노선을 회원은 참여할 수 있다.
- 본인이 생성한 노선은 참여할 수 없다.
- 좌석, 탑승 인원을 선택 할 수 있다.
- 금액, 소요 시간 표시된다.

## TODO
- [ ] 회원은 생성된 노선을 참여할 수 있다.
- [ ] 좌석, 탑승 인원을 선택 할 수 있다.
- [ ] 금액, 소요 시간 표시된다.
- [ ] 출발지 추가 여부를 선택할 수 있다.
