### ISSUE TITLE
ROUTE/노선 상세정보 조회

### ISSUE THREAD

**Issue by gibbeunLee** [jungo0/Budy#25]
## 요구사항 ID
ROUTE/노선상세정보 조회

## 요구사항
회원의 하나의 단일노선에 대한 상세정보를 조회 할 수 있다.

## 상세 요구사항
- 상세정보 사항으로는 아래와 같다.
- 출발지 로드맵, 노선명, 출발지, 목적지, 출발시간, 출발일자
- 노선 운행 정보, 운행 기사 상세 정보
- 출발지, 목적지 예상 도착시간
- 개설 노선과 일반 대중교통 소요 시간 비교
- 단일노선의 출발지는 회원별 하나의 출발지만 등록 가능하다.

## TODO
- [ ] 출발지 로드맵, 노선명, 출발지, 목적지, 출발시간, 출발일자를 조회 할 수 있다.
- [ ] 노선 운행 정보, 운행 기사 상세 정보를 조회 할 수 있다.
- [ ] 출발지, 목적지 예상 도착시간을 조회 할 수 있다.
- [ ] 개설 노선과 일반 대중교통 소요 시간 비교, 조회 할 수 있다.
- [ ] 출발지 추가 생성자는 추가 불가
